min_version = "2025.11.3"

# Sources:
# - https://mise.jdx.dev/mise-cookbook/nodejs.html

[tools]
node = "24.12.0"
pnpm = "10.28.0"

[settings]
# This must be enabled to make the hooks work
experimental = true

[hooks]
enter = '''
set -x
git pull || (git fetch; git status)
pnpm i
ls node_modules/.bin
if [[ -f ~/.bashrc ]] && ! grep "$PWD/alias" ~/.bashrc; then
    echo "to add node_modules/.bin to your PATH and add alises run"
    echo 'echo ". $PWD/alias" >> ~/.bashrc'
    echo "and restart the terminal!"
fi
'''